services:
    mariadb:
        image: mariadb:12.1.2
        restart: always
        ports:
            - "3000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "Exposed_password_1!"
            MYSQL_DATABASE: "testdb"
