services:
    mysql8:
        image: mysql:8.4
        restart: always
        ports:
            - "3002:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "Exposed_password_1!"
            MYSQL_DATABASE: "testdb"
