version: '3.1'

services:
    mariadb:
        image: mariadb
        ports:
            - "3000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "Exposed_password_1!"
            MYSQL_DATABASE: "testdb"
